
import numpy as np
from numpy.polynomial.laguerre import laggauss
from numpy.polynomial.legendre import leggauss

# from main import frange
def frange(start, stop, step):
    x = start
    if step > 0:
        while x <= stop + 1e-12:
            yield x
            x += step
    else:
        while x >= stop - 1e-12:
            yield x
            x += step

def build_s_shells(rAB, Ks, s_max, gamma=3.0):  # (Yes, leggauss is used on purpose. It works better than laggauss here, somehow.)
    s_min = 2.0 * rAB

    x, w = leggauss(Ks)         # [-1,1]
    u = 0.5*(x + 1.0)           # [0,1]
    wu = 0.5*w

    s = s_min + (s_max - s_min) * (u**gamma)
    ds_du = (s_max - s_min) * gamma * (u**(gamma - 1.0))
    ws = wu * ds_du
    return s, ws

def split_s(s, rAB, Ku, gamma = 6.0):
    """
    Deterministic split of total s into s1,s2.
    s1 ∈ [rAB, s-rAB], s2 = s - s1.
    rAB is the full internuclear distance R.
    """
    if gamma < 1.0:
        raise ValueError("gamma must be >= 1.0")

    # Gauss-Legendre on [-1,1]
    x, w = leggauss(Ku)

    xg = np.sign(x) * np.abs(x)**gamma  # Power-around-center on [-1,1]

    if gamma == 1.0:   # Jacobian dxg/dx
        J = np.ones_like(x)
    else:
        J = gamma * np.abs(x)**(gamma - 1.0)

    u = 0.5 * (xg + 1.0)  # Map to u ∈ [0,1]
    span = s - 2.0 * rAB
    s1 = rAB + u * span
    s2 = s - s1
    w_split = 0.5 * w * J * span

    return s1, s2, w_split

def split_s_old(s, rAB, Ku):
    """
    Deterministic split of total s into s1,s2.
    s1 ∈ [rAB, s-rAB], s2 = s - s1.
    rAB is the full internuclear distance R.
    """
    x, w = leggauss(Ku)       # nodes in [-1,1]
    u = 0.5 * (x + 1.0)       # map to [0,1]
    wu = 0.5 * w              # du weights on [0,1]

    # Map u -> s1 in [rAB, s-rAB]
    s1 = rAB + u * (s - 2.0*rAB)
    s2 = s - s1
    w_split = (s - 2.0*rAB) * wu

    return s1, s2, w_split

def shell_area_weight(s1, s2, rAB):
    shell_area_1 = 4*np.pi*((s1 / rAB)**2 - 1/3)
    shell_area_2 = 4*np.pi*((s2 / rAB)**2 - 1/3)
    return shell_area_1 * shell_area_2

def sample_s_shell(rAB, s, nMu=12, Nphi=32, octant=False, s1 = 1.0):
    """
    Deterministic quadrature on the prolate spheroidal shell rA+rB = s.
    Returns (x,y,z, w) arrays of length nMu*Nphi.

    R = full internuclear distance (same R used in mu=s/R)
    """
    if octant: # todo: test further
        ds = np.abs(s-s1)  # difference between s1, s2 (small ds -> check more small phi values for small r12)
        gamma_phi = gamma_phi_from_ds(ds, gamma_max=20.)
        return sample_s_shell_phi_bias_octant(rAB, s, int(nMu*1.3), Nphi*int(gamma_phi), gamma_phi) # * int(np.sqrt(gamma_phi))
        # return sample_s_shell_phi_bias_octant(rAB, s, nMu, Nphi, 3.0) # todo: the 1.3 factor helped a lot too

    mu = s / rAB

    nu0, w0 = leggauss(nMu)
    a, b = (0, 1) if octant else (-1, 1)
    nu = 0.5*(b-a)*nu0 + 0.5*(a+b)
    wnu = 0.5*(b-a)*w0 * (2 if octant else 1)  # (Immediately undo half-weighting, since octant will be mirrored back)

    # phi trapezoid grid on [0,2π)
    pa, pb = (0, np.pi/2) if octant else (0, 2*np.pi)
    phi = pa + (pb-pa)/Nphi * np.arange(Nphi)
    wphi = (pb-pa)/Nphi * (4 if octant else 1)

    # tensor product grid
    nu_grid = np.repeat(nu, Nphi)
    phi_grid = np.tile(phi, nMu)

    # shell Jacobian factor
    jac = (mu*mu - nu_grid*nu_grid)

    # total quadrature weight for each (nu,phi)
    w = np.repeat(wnu, Nphi) * wphi * jac

    # map to Cartesian (nuclei on x-axis at ±R/2)
    x = 0.5 * rAB * mu * nu_grid
    rho = 0.5 * rAB * np.sqrt((mu*mu - 1.0) * (1.0 - nu_grid*nu_grid))
    y = rho * np.cos(phi_grid)
    z = rho * np.sin(phi_grid) if Nphi > 2 else np.zeros_like(x)

    return x, y, z, nu_grid, phi_grid, w


def sample_s_shell_octant_mc(
    rAB, s, ds,
    N=4096,
    gamma_max=6.0,
    d0=None,
    stratified=True,
    seed=0,
):
    """
    Monte-Carlo / stratified importance sampling on the octant for a fixed prolate shell rA+rB = s.

    Samples:
      nu in [0,1], phi in [0,pi/2)

    Proposal:
      nu ~ Uniform(0,1)
      phi generated by phi = (pi/2) * u^gamma, u ~ Uniform(0,1)
      where gamma = gamma_phi_from_ds(ds)

    Weights implement:
      ∫_0^1 ∫_0^{pi/2} f(nu,phi) (mu^2-nu^2) dphi dnu * 4
    so that downstream you can just do sum_i w_i * f_i.

    Returns: x,y,z, nu,phi, w   (arrays length N)
    """
    mu = s / rAB
    if d0 is None:
        d0 = 0.2 * rAB  # sensible default scale

    gamma_phi = gamma_phi_from_ds(ds, d0=d0, gamma_max=gamma_max)

    rng = np.random.default_rng(seed)

    # ---- sample nu, u with optional stratification ----
    if stratified:
        # 1D stratification for nu and u (phi), cheap and effective
        i = np.arange(N)
        nu = (i + rng.random(N)) / N
        u  = (rng.permutation(N) + rng.random(N)) / N  # permute to decorrelate
    else:
        nu = rng.random(N)
        u  = rng.random(N)

    # ---- phi importance map: phi = (pi/2) * u^gamma ----
    phi = 0.5*np.pi * (u ** gamma_phi)

    # proposal pdfs
    q_nu = np.ones_like(nu)  # uniform on [0,1]
    # u uniform -> phi pdf = du/dphi
    # u = (phi/(pi/2))^(1/gamma)
    # du/dphi = (1/gamma) * (2/pi)^(1/gamma) * phi^(1/gamma - 1)
    # safe formula using u: du/dphi = 1 / (dphi/du)
    dphi_du = 0.5*np.pi * gamma_phi * (u ** (gamma_phi - 1.0))
    q_phi = 1.0 / dphi_du

    # shell Jacobian factor (same as your deterministic code)
    jac = (mu*mu - nu*nu)

    # MC weights for the angular integral over the octant
    w = 4.0 * jac / (N * (q_nu * q_phi))

    # coordinates (same mapping you use)
    x = 0.5 * rAB * mu * nu
    rho = 0.5 * rAB * np.sqrt((mu*mu - 1.0) * (1.0 - nu*nu))
    y = rho * np.cos(phi)
    z = rho * np.sin(phi)

    return x, y, z, nu, phi, w

def gamma_phi_from_ds(ds, d0 = 0.4, gamma_max = 8.0):  # compute phi clustering parameter from ds = s1-s2 (big clustering for small ds)
    return 1.0 + (gamma_max - 1.0) / (1.0 + (ds / d0)**2)

def sample_s_shell_phi_bias_octant(rAB, s, nMu=12, Nphi=16, gamma_phi=3.0):
    """
    Like sample_s_shell(..., octant=True) but with phi clustered near 0
    using phi = (pi/2) * u^p, u uniform in [0,1).
    Weights include dphi/du Jacobian and the usual (mu^2-nu^2).
    """
    mu = s / rAB

    # nu in [0,1] for octant, with mirrored weight factor handled outside (same as your code)
    nu0, w0 = leggauss(nMu)
    a, b = 0.0, 1.0
    nu = 0.5*(b-a)*nu0 + 0.5*(a+b)
    wnu = 0.5*(b-a)*w0 * 2.0  # undo halfing of nu space in weight

    # biased phi on [0, pi/2)
    u = (np.arange(Nphi) + 0.5) / Nphi          # midpoint rule in u
    phi = (0.5*np.pi) * (u ** gamma_phi)
    wphi = (0.5*np.pi) * gamma_phi * (u ** (gamma_phi - 1.0)) * (1.0 / Nphi)
    wphi = wphi * 4.0  # octant mirroring factor

    nu_grid = np.repeat(nu, Nphi)
    phi_grid = np.tile(phi, nMu)

    jac = (mu*mu - nu_grid*nu_grid)
    w = np.repeat(wnu, Nphi) * np.tile(wphi, nMu) * jac

    x = 0.5 * rAB * mu * nu_grid
    rho = 0.5 * rAB * np.sqrt((mu*mu - 1.0) * (1.0 - nu_grid*nu_grid))
    y = rho * np.cos(phi_grid)
    z = rho * np.sin(phi_grid)

    return x,y,z,nu_grid,phi_grid,w




# for alpha in frange(0.75, 0.75, 0.01):
#     S = np.zeros((matSize, matSize), dtype=np.float64)
#     H = np.zeros((matSize, matSize), dtype=np.float64)
#
#     # alpha = 0.74
#     beta = 0
#
#     for (rAB, s), Sl in S_layers.items(): S += Sl * np.exp(-2*alpha*s - 2*beta*rAB)
#     for (rAB, s), Hl in H_1_layers.items(): H += Hl * np.exp(-2*alpha*s - 2*beta*rAB)
#     for (rAB, s), Hl in H_alpha_layers.items(): H += Hl * alpha * np.exp(-2*alpha*s - 2*beta*rAB)
#     for (rAB, s), Hl in H_alpha_2_layers.items(): H += Hl * alpha**2 * np.exp(-2*alpha*s - 2*beta*rAB)
#     for (rAB, s), Hl in H_alpha_beta_layers.items(): H += Hl * alpha*beta * np.exp(-2*alpha*s - 2*beta*rAB)
#     for (rAB, s), Hl in H_beta_layers.items(): H += Hl * beta * np.exp(-2*alpha*s - 2*beta*rAB)
#     for (rAB, s), Hl in H_beta_2_layers.items(): H += Hl * beta**2 * np.exp(-2*alpha*s - 2*beta*rAB)
#
#     H, S = diag_rescale_generalized(H, S)
#
#     eigvals = np.linalg.eigvalsh(S)
#     # print("After Diag rescaling:")
#     # print(eigvals)
#     # print("min eig:", np.abs(eigvals).min())
#     # print("max eig:", np.abs(eigvals).max())
#     print(f"\nalpha = {alpha}, cond: {eigvals.max() / eigvals.min():.3e}")
#
#     # inspect_small_overlap_eigenvectors(S)
#
#     h_idx = basis_idx[:, 0]
#     k_idx = basis_idx[:, 1]
#     n_idx = basis_idx[:, 2]
#     m_idx = basis_idx[:, 3]
#     i_idx = basis_idx[:, 4]
#     j_idx = basis_idx[:, 5]
#
#     E, C = eig(H, S)
#     idx = np.argsort(E)
#     E = np.real(E[idx])
#     C = np.real(C[:, idx])
#
#     i = 0
#     while i < len(E) and E[i] < 0:
#         ci = C[:, i]
#         ci = ci/ci[0]
#         # hp = test_A @ ci
#         # p = test_B @ ci
#
#         eps = np.linalg.norm(H @ ci - E[i] * (S @ ci)) / (np.linalg.norm(H @ ci) + 1e-30)
#         print(f"E[{i}] := {E[i]}: epsilon[{i}] := {eps}: "
#               # f"C[{i}] := {[f' + ({float(x)}) * rAB^{h_idx[ii]}*r12^{k_idx[ii]}*s^{n_idx[ii]}*t^{m_idx[ii]}*mu1^{i_idx[ii]}*mu2^{j_idx[ii]}' for ii, x in enumerate(ci)]}")
#               f"C[{i}] := " + "".join( f" + ({float(x)})*rAB^{h_idx[ii]}*r12^{k_idx[ii]}*s^{n_idx[ii]}*t^{m_idx[ii]}*mu1^{i_idx[ii]}*mu2^{j_idx[ii]}" for ii, x in enumerate(ci)) )
#         i += 1
#
#     x = x1_all
#     y = y1_all
#     rAB = plot_rAB_target
#     s = plot_s2_target + np.sqrt((x + 0.5 * rAB) ** 2 + y ** 2) + np.sqrt((x - 0.5 * rAB) ** 2 + y ** 2)
#
#     plot_phi_and_local_energy_mu2(
#         x1_all, y1_all, mu2_all,
#         B_plot_all,
#         A_1_all,
#         A_alpha_all,
#         A_beta_all,
#         A_alpha2_all,
#         A_alphabeta_all,
#         A_beta2_all,
#         rAB = plot_rAB_target,
#         phi = plot_phi_target,
#         s2 = plot_s2_target,
#         exps = np.exp(-alpha * s - beta * rAB)[:, None],
#         C = C, E = E,
#         alpha=alpha, beta=beta, zlim_eloc=(-3, 0)
#     )

import numpy as np
from math import factorial

def _mu_int(n: int, p: float) -> float:
    # ∫_1^∞ μ^n e^{-pμ} dμ = e^{-p} Σ_{j=0..n} n!/(n-j)! * 1/p^{j+1}
    nfac = factorial(n)
    s = 0.0
    for j in range(n + 1):
        s += nfac / factorial(n - j) / (p ** (j + 1))
    return np.exp(-p) * s

def I3_exp(rAB: float, k: float) -> float:
    a = 0.5 * rAB
    p = k * rAB
    I2 = _mu_int(2, p)
    I0 = _mu_int(0, p)
    return 2*np.pi * a**3 * (2*I2 - (2/3)*I0)

def I3_s_exp(rAB: float, k: float) -> float:
    # ∫ s e^{-k s} dV = - d/dk I3
    # Since p=k rAB, d/dk = rAB d/dp
    a = 0.5 * rAB
    p = k * rAB

    # d/dp ∫ μ^n e^{-pμ} dμ = - ∫ μ^{n+1} e^{-pμ} dμ
    dI2_dp = -_mu_int(3, p)
    dI0_dp = -_mu_int(1, p)

    dI3_dp = 2*np.pi * a**3 * (2*dI2_dp - (2/3)*dI0_dp)
    return -(rAB * dI3_dp)
import numpy as np

def integrate_6d_via_split(rAB, s_max, Ks=48, Ku=32, Nnu=32, Nphi=64, f=None, gamma=2.0):
    """
    Numerically approximates ∫ f(...) d^3r1 d^3r2 over the domain s1>=R, s2>=R
    using your:
      build_s_shells(rAB, Ks, s_max, gamma)
      split_s(s, rAB, Ku)
      sample_s_shell(rAB, s1), sample_s_shell(rAB, s2)
    """
    # s_grid, ws = build_s_shells(rAB, Ks, s_max, gamma=gamma)  # :contentReference[oaicite:5]{index=5}
    s_grid, ws = build_s_shells(rAB, Ks)  # :contentReference[oaicite:5]{index=5}
    a = 0.5 * rAB
    pref = (a**3 / rAB)**2   # (a^3 dμ)^2 with dμ=ds/rAB  => overall rAB factors handled here

    total = 0.0
    for s, w_s in zip(s_grid, ws):
        s1, s2, w_split = split_s(s, rAB, Ku)  # :contentReference[oaicite:6]{index=6}
        for si, sj, w_ij in zip(s1, s2, w_split):
            x1,y1,z1,nu1,phi1,wsh1 = sample_s_shell(rAB, si, nMu=Nnu, Nphi=2, octant=False)  # :contentReference[oaicite:7]{index=7}
            x2,y2,z2,nu2,phi2,wsh2 = sample_s_shell(rAB, sj, nMu=Nnu, Nphi=32, octant=True, s1=s1)  # :contentReference[oaicite:8]{index=8}

            # evaluate on tensor product of shell grids
            if f is None:
                vals = 1.0
                block = np.sum(wsh1) * np.sum(wsh2)
            else:
                # build r12 if needed
                dx = x1[:,None]-x2[None,:]
                dy = y1[:,None]-y2[None,:]
                dz = z1[:,None]-z2[None,:]
                r12 = np.sqrt(dx*dx+dy*dy+dz*dz)

                vals = f(si, sj, s, x1,y1,z1, x2,y2,z2, r12)
                block = np.sum((wsh1[:,None]*wsh2[None,:]) * vals)

            total += w_s * w_ij * block

    return pref * total
def test_split_swap_zero(rAB=1.4, s_max=60.0, k=0.8):
    num = integrate_6d_via_split(
        rAB, s_max,
        f=lambda s1,s2,st, *args: (s1 - s2) * np.exp(-k*st)
    )
    print("swap-antisym (should be 0):", num)
def test_split_s1_moment(rAB=1.4, s_max=60.0, k=0.8):
    num_s1 = integrate_6d_via_split(
        rAB, s_max,
        f=lambda s1,s2,st, *args: (s1) * np.exp(-k*st)
    )
    num_s2 = integrate_6d_via_split(
        rAB, s_max,
        f=lambda s1,s2,st, *args: (s2) * np.exp(-k*st)
    )

    # exact over infinite range (your finite s_max should be large enough with exp decay)
    ex = I3_exp(rAB,k) * I3_s_exp(rAB,k)

    print("∫ s1 e^{-k(s1+s2)}:", num_s1)
    print("∫ s2 e^{-k(s1+s2)}:", num_s2)
    print("exact:", ex)
    print("relerr s1:", abs(num_s1-ex)/abs(ex))
    print("relerr s2:", abs(num_s2-ex)/abs(ex))
    print("swap diff (should be 0):", num_s1-num_s2)

def integrate_6d_gaussian_r12(rAB, alpha, beta, Kmu=22, Nnu=12, Nphi=24, p_map=1.2):
    """
    Generic μ quadrature: μ = 1 + t/p_map, t∈[0,∞).
    Uses Laguerre weights w (for ∫ e^{-t} g(t) dt), so to integrate ∫ f(t) dt we use g(t)=e^{t} f(t).
    """
    t, w = np.polynomial.laguerre.laggauss(Kmu)
    mu = 1.0 + t / p_map
    dmu = 1.0 / p_map

    a = 0.5 * rAB
    pref = (a**3 * dmu)**2

    total = 0.0
    for i, mui in enumerate(mu):
        s1 = mui * rAB
        x1,y1,z1,nu1,phi1,w1 = sample_s_shell(rAB, s1, nMu=Nnu, Nphi=2, octant=False)
        r1_2 = x1*x1 + y1*y1 + z1*z1

        for j, muj in enumerate(mu):
            s2 = muj * rAB
            x2,y2,z2,nu2,phi2,w2 = sample_s_shell(rAB, s2, nMu=12, Nphi=24, octant=True, s1=s1)
            r2_2 = x2*x2 + y2*y2 + z2*z2

            dx = x1[:,None]-x2[None,:]
            dy = y1[:,None]-y2[None,:]
            dz = z1[:,None]-z2[None,:]
            r12_2 = dx*dx+dy*dy+dz*dz

            integrand = np.exp(-alpha*(r1_2[:,None] + r2_2[None,:]) - beta*r12_2)
            block = np.sum((w1[:,None]*w2[None,:]) * integrand)

            # convert Laguerre to plain dt integral: multiply by exp(t_i+t_j)
            total += (w[i]*np.exp(t[i])) * (w[j]*np.exp(t[j])) * block

    return pref * total

def exact_6d_gaussian(alpha, beta):
    return (np.pi**3) / ((alpha*(alpha+2.0*beta))**1.5)

def test_r12_gaussian(rAB=1.4, alpha=0.7, beta=0.4):
    num = integrate_6d_gaussian_r12(rAB, alpha, beta)
    ex  = exact_6d_gaussian(alpha, beta)
    print("6D Gaussian(r12) num:", num)
    print("6D Gaussian(r12) exact:", ex)
    print("relerr:", abs(num-ex)/abs(ex))
def exact_6d_gaussian_r12sq(alpha, beta):
    I = exact_6d_gaussian(alpha, beta)
    return (3.0/(alpha+2.0*beta)) * I

def test_r12_moment(rAB=1.4, alpha=0.7, beta=0.4):
    def integrate_r12sq():
        t, w = np.polynomial.laguerre.laggauss(22)
        p_map=1.2
        mu = 1.0 + t / p_map
        dmu = 1.0 / p_map
        a = 0.5*rAB
        pref = (a**3*dmu)**2

        total = 0.0
        for i, mui in enumerate(mu):
            s1 = mui*rAB
            x1,y1,z1,nu1,phi1,w1 = sample_s_shell(rAB, s1, nMu=12, Nphi=2, octant=False)
            r1_2 = x1*x1 + y1*y1 + z1*z1
            for j, muj in enumerate(mu):
                s2 = muj*rAB
                x2,y2,z2,nu2,phi2,w2 = sample_s_shell(rAB, s2, nMu=12, Nphi=24, octant=True, s1=s1)
                r2_2 = x2*x2 + y2*y2 + z2*z2

                dx = x1[:,None]-x2[None,:]
                dy = y1[:,None]-y2[None,:]
                dz = z1[:,None]-z2[None,:]
                r12_2 = dx*dx+dy*dy+dz*dz

                base = np.exp(-alpha*(r1_2[:,None]+r2_2[None,:]) - beta*r12_2)
                block = np.sum((w1[:,None]*w2[None,:]) * (r12_2 * base))

                total += (w[i]*np.exp(t[i]))*(w[j]*np.exp(t[j])) * block

        return pref * total

    num = integrate_r12sq()
    ex  = exact_6d_gaussian_r12sq(alpha, beta)
    print("6D r12^2 moment num:", num)
    print("6D r12^2 moment exact:", ex)
    print("relerr:", abs(num-ex)/abs(ex))

import numpy as np
import matplotlib.pyplot as plt

def plot_r12_weight_cdf(
    rAB=1.4,
    nS=20,
    sMax=40.0,
    gamma=3.0,
    Ku=11,
    nMu=12,
    max_pairs=2_000_0000,
    seed=0,
):
    """
    Build the *actual* r12-weight distribution implied by your current sampling:
      build_s_shells -> split_s -> sample_s_shell(e1 in xy-plane) -> sample_s_shell(e2 octant)
    and plot:
      (1) CDF of total weight vs r12
      (2) weighted r12 histogram mass (log-y)

    Weight per pair is exactly:
        W = sW[ks] * splitW[j] * w1[i] * w2[j]
    which mirrors how main.py passes sW[ks]*splitW[j] into calc_AB and combines with w1,w2 there.
    """

    rng = np.random.default_rng(seed)

    s_shells, sW = build_s_shells(rAB, Ks=nS, s_max=sMax)

    r12_chunks = []
    w_chunks = []
    total_pairs = 0

    for ks, s in enumerate(s_shells):
        s1_vals, s2_vals, splitW = split_s(s, rAB, Ku=11, gamma = 3.0)

        outer_w = sW[ks]

        for j_split, (s1, s2) in enumerate(zip(s1_vals, s2_vals)):
            # electron 1: xy plane only (Nphi=2)
            x1, y1, z1, mu1, phi1, w1 = sample_s_shell(rAB, s1, Nphi=2, nMu=nMu, octant=False)

            # electron 2: octant (your biased-phi version is inside sample_s_shell now)
            x2, y2, z2, mu2, phi2, w2 = sample_s_shell(rAB, s2, Nphi=24, nMu=nMu, octant=True, s1=s1)

            W_outer = outer_w * splitW[j_split]

            dx = x1[:, None] - x2[None, :]
            dy = y1[:, None] - y2[None, :]
            dz = z1[:, None] - z2[None, :]
            r12 = np.sqrt(dx*dx + dy*dy + dz*dz)

            W = (W_outer * w1[:, None] * w2[None, :])

            flat_r12 = r12.ravel()
            flat_W = W.ravel()

            n = flat_r12.size
            if total_pairs + n > max_pairs:
                remaining = max_pairs - total_pairs
                if remaining <= 0:
                    break
                idx = rng.choice(n, size=remaining, replace=False)
                flat_r12 = flat_r12[idx]
                flat_W = flat_W[idx]
                n = remaining

            r12_chunks.append(flat_r12.astype(np.float64, copy=False))
            w_chunks.append(flat_W.astype(np.float64, copy=False))
            total_pairs += n

        if total_pairs >= max_pairs:
            break

    r12_all = np.concatenate(r12_chunks) if r12_chunks else np.array([], dtype=np.float64)
    w_all = np.concatenate(w_chunks) if w_chunks else np.array([], dtype=np.float64)

    mask = np.isfinite(r12_all) & np.isfinite(w_all) & (w_all > 0)
    r12_all = r12_all[mask]
    w_all = w_all[mask]

    if r12_all.size == 0:
        raise RuntimeError("No samples collected. Check your sampling parameters.")

    # CDF
    order = np.argsort(r12_all)
    r_sorted = r12_all[order]
    w_sorted = w_all[order]
    cdf = np.cumsum(w_sorted)
    cdf /= cdf[-1]

    plt.figure()
    plt.plot(r_sorted, cdf)
    plt.xlabel("r12")
    plt.ylabel("Cumulative weight fraction (<= r12)")
    plt.title(f"Weight CDF vs r12  (rAB={rAB}, pairs≈{r_sorted.size})")
    plt.grid(True)
    plt.show()

    # Weighted histogram mass (log-y)
    bins = np.linspace(0.0, np.percentile(r12_all, 99.9), 200)
    hist, edges = np.histogram(r12_all, bins=bins, weights=w_all)
    centers = 0.5*(edges[:-1] + edges[1:])
    hist = hist / np.sum(hist)

    plt.figure()
    plt.semilogy(centers, hist + 1e-300)
    plt.xlabel("r12")
    plt.ylabel("Weighted bin mass (log scale)")
    plt.title("Weighted r12 distribution (mass per bin, not /Δr)")
    plt.grid(True)
    plt.show()
    #
    # eps = 1e-12
    # wC = w_all / np.maximum(r12_all, eps)
    #
    # # raw CDF
    # order = np.argsort(r12_all)
    # r = r12_all[order]
    # w = w_all[order]
    # cdf = np.cumsum(w) / np.sum(w)
    #
    # # Coulomb CDF
    # wC_sorted = wC[order]
    # cdfC = np.cumsum(wC_sorted) / np.sum(wC_sorted)
    #
    # plt.figure()
    # plt.plot(r, cdf, label="raw W")
    # plt.plot(r, cdfC, label="Coulomb W/r12")
    # plt.xlabel("r12")
    # plt.ylabel("CDF")
    # plt.grid(True)
    # plt.legend()
    # plt.show()

    return r_sorted, cdf, centers, hist
import numpy as np
import matplotlib.pyplot as plt


import numpy as np
import matplotlib.pyplot as plt


def plot_r12_weight_vs_r2(
    rAB=1.4,
    nS=40,
    sMax=50.0,
    gamma_s=3.0,
    Ku=11,
    gamma_split=6.0, # todo: helps a lot
    nMu=32,
    Nphi1=2,
    Nphi2=24,
    r_plot_max=10.0,
    nbins=220,
    max_pairs=200_000_000,
    seed=0,
    # fit window used to determine the unknown constant C in C*r^2
    r_fit_min=0.015,
    r_fit_max=0.3,
):
    """
    Plots the *effective sampled* r12 weight density dW/dr against the
    geometric expectation ~ C * r^2 (C fitted on [r_fit_min, r_fit_max]),
    focusing on r <= r_plot_max (e.g. 10).

    Why this is the right comparison:
      - Your quadrature induces a measure on r12 with density dW/dr.
      - Near r12->0 the correct scaling is r^2 (3D relative volume element).
      - The overall constant C is not known a priori, so we fit it.
      - We only care about accuracy up to r_plot_max because your integrands
        decay at large s (thus large r12 contribute little anyway).

    Requirements:
      build_s_shells, split_s, sample_s_shell must exist in the namespace.

    Returns:
      centers, density, ref_density, ratio
    """

    rng = np.random.default_rng(seed)

    # --- collect r12 and weights exactly as your integrator would weight them ---
    s_shells, sW = build_s_shells(rAB, Ks=nS, s_max=sMax, gamma=gamma_s)

    r12_chunks, w_chunks = [], []
    total_pairs = 0

    for ks, s in enumerate(s_shells):
        s1_vals, s2_vals, splitW = split_s(s, rAB, Ku=Ku, gamma=gamma_split)
        outer_w = sW[ks]

        for j_split, (s1, s2) in enumerate(zip(s1_vals, s2_vals)):
            x1, y1, z1, *_ , w1 = sample_s_shell(rAB, s1, nMu=nMu, Nphi=Nphi1, octant=False)
            x2, y2, z2, *_ , w2 = sample_s_shell(rAB, s2, nMu=nMu, Nphi=Nphi2, octant=True,  s1=s1)

            W_outer = outer_w * splitW[j_split]

            dx = x1[:, None] - x2[None, :]
            dy = y1[:, None] - y2[None, :]
            dz = z1[:, None] - z2[None, :]
            r12 = np.sqrt(dx*dx + dy*dy + dz*dz)

            W = W_outer * w1[:, None] * w2[None, :]

            flat_r = r12.ravel()
            flat_w = W.ravel()

            m = np.isfinite(flat_r) & np.isfinite(flat_w) & (flat_w > 0) & (flat_r > 0)
            flat_r = flat_r[m]
            flat_w = flat_w[m]

            n = flat_r.size
            if total_pairs + n > max_pairs:
                keep = max_pairs - total_pairs
                if keep <= 0:
                    break
                idx = rng.choice(n, size=keep, replace=False)
                flat_r = flat_r[idx]
                flat_w = flat_w[idx]
                n = keep

            r12_chunks.append(flat_r.astype(np.float64, copy=False))
            w_chunks.append(flat_w.astype(np.float64, copy=False))
            total_pairs += n

        if total_pairs >= max_pairs:
            break

    if not r12_chunks:
        raise RuntimeError("No samples collected. Increase max_pairs or check parameters.")

    r12_all = np.concatenate(r12_chunks)
    w_all = np.concatenate(w_chunks)

    # --- build a density dW/dr on [min, r_plot_max] with log bins (so small-r is visible) ---
    rmin = max(np.min(r12_all), 1e-6)
    rmax = min(r_plot_max, np.max(r12_all))
    if rmax <= rmin:
        raise RuntimeError("r_plot_max too small or no r12 support.")

    edges = np.geomspace(rmin, rmax, nbins + 1)
    mass, _ = np.histogram(r12_all, bins=edges, weights=w_all)
    widths = np.diff(edges)
    centers = np.sqrt(edges[:-1] * edges[1:])

    # density: mass per unit r (not normalized to 1 unless you choose to)
    density = mass / widths

    # --- fit the unknown constant C in C*r^2 on a user-chosen window ---
    fit_mask = (centers >= r_fit_min) & (centers <= r_fit_max) & np.isfinite(density) & (density > 0)
    if np.count_nonzero(fit_mask) < 5:
        raise RuntimeError("Not enough bins in fit window; adjust r_fit_min/r_fit_max or nbins.")

    # least squares fit: density ~ C * r^2
    x = centers[fit_mask]**2
    y = density[fit_mask]
    C = np.dot(x, y) / np.dot(x, x)

    ref_density = C * centers**2
    ratio = density / np.maximum(ref_density, 1e-300)

    # --- plots ---
    plt.figure()
    plt.loglog(centers, density, label="sampled dW/dr (weighted)")
    plt.loglog(centers, ref_density, "--", label=f"fitted C·r^2  (fit {r_fit_min}..{r_fit_max})")
    plt.xlabel("r12")
    plt.ylabel("dW/dr  (weight density)")
    plt.title(f"r12 weight density vs C·r^2  (r<= {rmax:g}, pairs≈{len(r12_all):,})")
    plt.grid(True, which="both")
    plt.legend()
    plt.show()

    plt.figure()
    plt.semilogx(centers, ratio)
    plt.axhline(1.0, color="k", ls="--")
    plt.xlabel("r12")
    plt.ylabel("sampled / (C·r^2)")
    plt.title("Shape error vs r^2 (flat=good)")
    plt.grid(True, which="both")
    plt.show()

    # # --- a small-r slope diagnostic that’s actually meaningful ---
    # # Fit slope of CDF in a small region (should be ~3 if relative DOFs are OK)
    # order = np.argsort(r12_all)
    # r_sorted = r12_all[order]
    # w_sorted = w_all[order]
    # cdf = np.cumsum(w_sorted)
    # cdf /= cdf[-1]
    #
    # # Use a small window relative to r_plot_max; tweak if needed
    # r_slope_max = min(0.25, rmax * 0.05)
    # m = (r_sorted > 0) & (r_sorted < r_slope_max) & (cdf > 0)
    # slope = np.nan
    # if np.count_nonzero(m) >= 20:
    #     slope = np.polyfit(np.log(r_sorted[m]), np.log(cdf[m]), 1)[0]
    #
    # print(f"\nFitted C for C·r^2: {C:.6e}")
    # print(f"Small-r CDF slope on (0, {r_slope_max:g}): {slope:.3f} (ideal ~3 if unconstrained)")
    #
    # # Weighted quantiles up to r_plot_max: super sensitive to small-r changes
    # def wquant(q):
    #     cw = np.cumsum(w_sorted)
    #     cw /= cw[-1]
    #     return np.interp(q, cw, r_sorted)
    #
    # print("Weighted r12 quantiles:")
    # for q in [1e-4, 1e-3, 1e-2, 5e-2, 1e-1, 5e-1]:
    #     print(f"  q={q:>7g}: {wquant(q):.6e}")
    #
    # return centers, density, ref_density, ratio


plot_r12_weight_vs_r2()
print("--")
test_r12_gaussian()
test_r12_moment()
# plot_r12_measure_diagnostics()
# plot_r12_weight_cdf(rAB=1.4, nS=40, sMax=50, gamma=3.0, Ku=10, nMu=24)
# test_split_swap_zero()
# test_split_s1_moment()